apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crusoe-lb-controller-binding
subjects:
  - kind: ServiceAccount
    name: crusoe-lb-controller-controller-manager
    namespace: crusoe-load-balancer-controller-system
roleRef:
  kind: ClusterRole
  name: crusoe-lb-controller-role
  apiGroup: rbac.authorization.k8s.io
