apiVersion: v1
kind: Service
metadata:
  name: svc3
  namespace: default
  annotations:
    crusoe.com/vpc-id: "406e04ef-164c-4746-8ede-496a46400278" # Replace with actual VPC ID
spec:
  selector:
    app: app
  ports:
  - name: http
    port: 81
    targetPort: 8080
  type: LoadBalancer
