# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ubuntu
#   namespace: default
# spec:
#   selector:
#     matchLabels:
#       app: app
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: app
#     spec:
#       containers:
#       - name: app
#         image: ubuntu:22.04
#         ports:
#         - name: http
#           containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc3
  namespace: default
  annotations:
    crusoe.com/vpc-id: "a0f91cb2-fdba-45c8-b7e0-19d01738221a" 
spec:
  selector:
    app: app
  ports:
  - name: http
    port: 81
    targetPort: 8080
  type: LoadBalancer
